-- Biblioteca Juliano/Ana Clara - App V1
-- 1) Rode este arquivo em Supabase > SQL Editor > New query > Run

create extension if not exists pgcrypto;

create table if not exists public.perfis (
  id bigint generated by default as identity primary key,
  nome text not null unique,
  cor text default '#d6a84f',
  created_at timestamptz default now()
);

create table if not exists public.livros (
  id uuid primary key default gen_random_uuid(),
  codigo text unique not null,
  titulo text not null,
  autor text,
  tema text,
  subtema text,
  colecao text,
  volume text,
  editora_formato text,
  isbn text,
  paginas integer,
  ano integer,
  localizacao text,
  capa_url text,
  observacoes text,
  tags text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.leituras (
  id uuid primary key default gen_random_uuid(),
  livro_id uuid not null references public.livros(id) on delete cascade,
  perfil_id bigint not null references public.perfis(id) on delete cascade,
  lido boolean not null default false,
  nota numeric(3,1) check (nota is null or (nota >= 0 and nota <= 10)),
  favorito boolean not null default false,
  comentario text,
  data_inicio date,
  data_conclusao date,
  updated_at timestamptz default now(),
  unique (livro_id, perfil_id)
);

insert into public.perfis (nome, cor) values
('Juliano', '#d6a84f'),
('Ana Clara', '#f08ab8'),
('Daine', '#7dd3fc')
on conflict (nome) do update set cor = excluded.cor;

alter table public.perfis enable row level security;
alter table public.livros enable row level security;
alter table public.leituras enable row level security;

-- Uso familiar sem login: qualquer pessoa com o link pode ler e editar.
do $$ begin create policy "perfis_read" on public.perfis for select using (true); exception when duplicate_object then null; end $$;
do $$ begin create policy "perfis_write" on public.perfis for all using (true) with check (true); exception when duplicate_object then null; end $$;
do $$ begin create policy "livros_read" on public.livros for select using (true); exception when duplicate_object then null; end $$;
do $$ begin create policy "livros_write" on public.livros for all using (true) with check (true); exception when duplicate_object then null; end $$;
do $$ begin create policy "leituras_read" on public.leituras for select using (true); exception when duplicate_object then null; end $$;
do $$ begin create policy "leituras_write" on public.leituras for all using (true) with check (true); exception when duplicate_object then null; end $$;

create or replace function public.set_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

drop trigger if exists livros_set_updated_at on public.livros;
create trigger livros_set_updated_at before update on public.livros for each row execute function public.set_updated_at();

drop trigger if exists leituras_set_updated_at on public.leituras;
create trigger leituras_set_updated_at before update on public.leituras for each row execute function public.set_updated_at();
