-- 2) Depois do schema, rode este arquivo para carregar os livros iniciais.
insert into public.livros (codigo, titulo, autor, tema, subtema, colecao, volume, editora_formato, isbn, paginas, ano, localizacao, capa_url, observacoes, tags) values
  ('LIV0001', 'O Gladiador', 'Hosana Pimentel Soares', 'Romance', 'Histórico', null, null, 'Livro físico', null, null, null, 'Estante 1 / Prateleira 2', null, null, null),
  ('LIV0002', 'Um Lindo Amor', 'Jeffrey Archer', 'Romance', 'Drama', null, null, 'Livro físico', null, null, null, 'Estante 1 / Prateleira 2', null, null, null),
  ('LIV0003', 'Mary Queen of Scots', 'Antonia Fraser', 'História', 'Biografia', null, null, 'Livro físico', null, null, null, 'Estante 1 / Prateleira 2', null, 'Título em inglês', null),
  ('LIV0004', 'Simplesmente Irresistível', 'Jill Mansell', 'Romance', 'Contemporâneo', null, null, 'Livro físico', null, null, null, 'Estante 1 / Prateleira 2', null, null, null),
  ('LIV0005', 'Tudo o que Ela Sempre Quis', 'Barbara Freethy', 'Romance', 'Contemporâneo', null, null, 'Livro físico', null, null, null, 'Estante 1 / Prateleira 2', null, null, null),
  ('LIV0006', 'Anos e Sagrados no Holocausto', 'Desconhecido', 'História', 'Segunda Guerra / Holocausto', null, null, 'Livro físico', null, null, null, 'Estante 1 / Prateleira 2', null, 'Conferir título e autor', null),
  ('LIV0007', 'O Amante de Lady Chatterley', 'D. H. Lawrence', 'Literatura Clássica', 'Romance', null, null, 'Livro físico', null, null, null, 'Estante 1 / Prateleira 2', null, null, null),
  ('LIV0008', 'Warren Buffett e a Análise de Balanços', 'Mary Buffett e David Clark', 'Negócios', 'Finanças / Investimentos', null, null, 'Livro físico', null, null, null, 'Estante 1 / Prateleira 2', null, null, null),
  ('LIV0009', 'A Ameaça do Mundo: O Amor, a Diplomacia...', 'Beth Revis', 'Ficção', 'Ficção científica / Romance', null, null, 'Livro físico', null, null, null, 'Estante 1 / Prateleira 2', null, 'Conferir título completo', null),
  ('LIV0010', 'Alguém Perfeito', 'Cristina Luz', 'Infantojuvenil', 'Romance', null, null, 'Livro físico', null, null, null, 'Estante 1 / Prateleira 2', null, null, null),
  ('LIV0011', 'Orgulho e Preconceito', 'Jane Austen', 'Literatura Clássica', 'Romance', null, null, 'Livro físico', null, null, null, 'Estante 1 / Prateleira 2', null, null, null),
  ('LIV0012', 'Para Todos os Garotos que Já Amei', 'Jenny Han', 'Romance', 'Young adult', 'Para Todos os Garotos que Já Amei', '1', 'Livro físico', null, null, null, 'Estante 1 / Prateleira 2', null, null, null),
  ('LIV0013', 'P.S. Ainda Amo Você', 'Jenny Han', 'Romance', 'Young adult', 'Para Todos os Garotos que Já Amei', '2', 'Livro físico', null, null, null, 'Estante 1 / Prateleira 2', null, null, null),
  ('LIV0014', 'Agora e Para Sempre, Lara Jean', 'Jenny Han', 'Romance', 'Young adult', 'Para Todos os Garotos que Já Amei', '3', 'Livro físico', null, null, null, 'Estante 1 / Prateleira 2', null, null, null),
  ('LIV0015', 'Amor e Azeitonas', 'Jenna Evans Welch', 'Romance', 'Young adult', 'Coleção Amor &', '3', 'Intrínseca', null, null, null, 'Estante 1 / Prateleira 2', null, null, null),
  ('LIV0016', 'Estamos Bem', 'Nina LaCour', 'Romance', 'Young adult / Drama', null, null, 'Livro físico', null, null, null, 'Estante 1 / Prateleira 2', null, null, null),
  ('LIV0017', 'Processo Civil', 'Desconhecido', 'Direito', 'Processo Civil', null, null, 'Livro físico', null, null, null, 'Estante 1 / Prateleira 2', null, 'Conferir autor', null),
  ('LIV0018', 'Teoria Geral do Direito Civil e Processo do Conhecimento', 'Maria Helena Diniz', 'Direito', 'Direito Civil / Processo', null, '1', 'Saraiva', null, null, null, 'Estante 1 / Prateleira 2', null, null, null),
  ('LIV0019', 'Curso de Direito Civil Brasileiro: Teoria Geral das Obrigações', 'Maria Helena Diniz', 'Direito', 'Direito Civil', null, '3', 'Saraiva', null, null, null, 'Estante 1 / Prateleira 2', null, null, null),
  ('LIV0020', 'Direito das Coisas', 'Maria Helena Diniz', 'Direito', 'Direito Civil', null, '5', 'Saraiva', null, null, null, 'Estante 1 / Prateleira 2', null, null, null),
  ('LIV0021', 'A Senhora do Jogo', 'Sidney Sheldon', 'Suspense', 'Drama / Mistério', null, null, 'Livro físico', null, null, null, 'Estante 1 / Prateleira 2', null, null, null),
  ('LIV0022', 'A Outra Face', 'Sidney Sheldon', 'Suspense', 'Mistério', null, null, 'Livro físico', null, null, null, 'Estante 1 / Prateleira 2', null, null, null),
  ('LIV0023', 'O Plano Perfeito', 'Sidney Sheldon', 'Suspense', 'Drama político', null, null, 'Livro físico', null, null, null, 'Estante 1 / Prateleira 2', null, null, null),
  ('LIV0024', 'O Outro Lado da Meia-Noite', 'Sidney Sheldon', 'Suspense', 'Drama', null, null, 'Livro físico', null, null, null, 'Estante 1 / Prateleira 2', null, null, null),
  ('LIV0025', 'O Reverso da Medalha', 'Sidney Sheldon', 'Suspense', 'Drama', null, null, 'Livro físico', null, null, null, 'Estante 1 / Prateleira 2', null, null, null),
  ('LIV0026', 'O Céu Está Caindo', 'Sidney Sheldon', 'Suspense', 'Mistério', null, null, 'Livro físico', null, null, null, 'Estante 1 / Prateleira 2', null, null, null),
  ('LIV0027', 'O Ditador', 'Desconhecido', 'Política / História', 'Biografia / Poder', null, null, 'Livro físico', null, null, null, 'Estante 1 / Prateleira 2', null, 'Conferir autor', null),
  ('LIV0028', 'O Código de Talento', 'Daniel Coyle', 'Desenvolvimento Pessoal', 'Aprendizagem / Alta performance', null, null, 'Livro físico', null, null, null, 'Estante 1 / Prateleira 2', null, null, null),
  ('LIV0029', 'Aprenda Inteligência Emocional', 'Desconhecido', 'Desenvolvimento Pessoal', 'Inteligência emocional', null, null, 'Livro físico', null, null, null, 'Estante 1 / Prateleira 2', null, 'Conferir título', null),
  ('LIV0030', 'Como Falar com Qualquer Pessoa', 'Leil Lowndes', 'Desenvolvimento Pessoal', 'Comunicação', null, null, 'Livro físico', null, null, null, 'Estante 1 / Prateleira 2', null, null, null),
  ('LIV0031', 'A Ira dos Justos', 'Desconhecido', 'Ficção', 'Suspense / Ação', null, null, 'Livro físico', null, null, null, 'Estante 1 / Prateleira 2', null, 'Conferir autor', null),
  ('LIV0032', 'A Menina que Roubava Livros', 'Markus Zusak', 'Literatura', 'Drama histórico', null, null, 'Livro físico', null, null, null, 'Estante 1 / Prateleira 2', null, null, null),
  ('LIV0033', 'O Que Faz Você Feliz?', 'Desconhecido', 'Desenvolvimento Pessoal', 'Reflexão', null, null, 'Livro físico', null, null, null, 'Estante 1 / Prateleira 2', null, 'Conferir autor', null),
  ('LIV0034', 'Bíblia', 'Vários autores', 'Religião', 'Cristianismo', null, null, 'Livro físico', null, null, null, 'Estante 1 / Prateleira 3', null, null, null),
  ('LIV0035', 'O Silmarillion', 'J. R. R. Tolkien', 'Fantasia', 'Alta fantasia', 'Legendarium de Tolkien', null, 'Livro físico', null, null, null, 'Estante 1 / Prateleira 3', null, null, null),
  ('LIV0036', 'A Batalha do Apocalipse', 'Eduardo Spohr', 'Fantasia', 'Fantasia épica', null, null, 'Livro físico', null, null, null, 'Estante 1 / Prateleira 3', null, null, null),
  ('LIV0037', 'Filhos do Éden: Herdeiros de Atlântida', 'Eduardo Spohr', 'Fantasia', 'Fantasia épica', 'Filhos do Éden', '1', 'Livro físico', null, null, null, 'Estante 1 / Prateleira 3', null, null, null),
  ('LIV0038', 'Necronomicon', 'H. P. Lovecraft', 'Terror', 'Horror cósmico', null, null, 'Livro físico', null, null, null, 'Estante 1 / Prateleira 3', null, null, null),
  ('LIV0039', 'Cidade dos Ossos', 'Cassandra Clare', 'Fantasia', 'Fantasia urbana', 'Os Instrumentos Mortais', '1', 'Livro físico', null, null, null, 'Estante 1 / Prateleira 3', null, null, null),
  ('LIV0040', 'Cidade das Cinzas', 'Cassandra Clare', 'Fantasia', 'Fantasia urbana', 'Os Instrumentos Mortais', '2', 'Livro físico', null, null, null, 'Estante 1 / Prateleira 3', null, null, null),
  ('LIV0041', 'Cidade de Vidro', 'Cassandra Clare', 'Fantasia', 'Fantasia urbana', 'Os Instrumentos Mortais', '3', 'Livro físico', null, null, null, 'Estante 1 / Prateleira 3', null, null, null),
  ('LIV0042', 'Cidade dos Anjos Caídos', 'Cassandra Clare', 'Fantasia', 'Fantasia urbana', 'Os Instrumentos Mortais', '4', 'Livro físico', null, null, null, 'Estante 1 / Prateleira 3', null, null, null),
  ('LIV0043', 'Cidade das Almas Perdidas', 'Cassandra Clare', 'Fantasia', 'Fantasia urbana', 'Os Instrumentos Mortais', '5', 'Livro físico', null, null, null, 'Estante 1 / Prateleira 3', null, null, null),
  ('LIV0044', 'Cidade do Fogo Celestial', 'Cassandra Clare', 'Fantasia', 'Fantasia urbana', 'Os Instrumentos Mortais', '6', 'Livro físico', null, null, null, 'Estante 1 / Prateleira 3', null, null, null),
  ('LIV0045', 'O Caçador do Deserto', 'Luciano Subirá', 'Religião', 'Cristianismo', null, null, 'Livro físico', null, null, null, 'Estante 1 / Prateleira 3', null, null, null),
  ('LIV0046', 'Hanah More: A Vendedora', 'Rebecca Hazell', 'Ficção', 'Histórico / Drama', null, null, 'Livro físico', null, null, null, 'Estante 1 / Prateleira 3', null, null, null),
  ('LIV0047', 'Michaels', 'Portuguesa Santista', 'Romance', 'Drama', null, null, 'Livro físico', null, null, null, 'Estante 1 / Prateleira 3', null, 'Conferir dados', null),
  ('LIV0048', 'Code of the Samurai', 'Desconhecido', 'História / Filosofia', 'Cultura japonesa', null, null, 'Livro físico', null, null, null, 'Estante 1 / Prateleira 3', null, null, null),
  ('LIV0049', 'Código de Processo Penal Anotado', 'Desconhecido', 'Direito', 'Processo Penal', null, null, 'Livro físico', null, null, null, 'Estante 1 / Prateleira 3', null, null, null),
  ('LIV0050', 'O Senhor dos Anéis: A Sociedade do Anel', 'J. R. R. Tolkien', 'Fantasia', 'Alta fantasia', 'O Senhor dos Anéis', '1', 'Livro físico', null, null, null, null, null, null, null),
  ('LIV0051', 'A Tormenta de Espadas', 'George R. R. Martin', 'Fantasia', 'Fantasia épica', 'As Crônicas de Gelo e Fogo', '3', 'Livro físico', null, null, null, null, null, null, null),
  ('LIV0052', 'A Dança dos Dragões', 'George R. R. Martin', 'Fantasia', 'Fantasia épica', 'As Crônicas de Gelo e Fogo', '5', 'Livro físico', null, null, null, null, null, null, null),
  ('LIV0053', 'A Batalha dos Reis', 'George R. R. Martin', 'Fantasia', 'Fantasia épica', 'As Crônicas de Gelo e Fogo', '2', 'Livro físico', null, null, null, null, null, null, null),
  ('LIV0054', 'As Mentiras de Locke Lamora', 'Scott Lynch', 'Fantasia', 'Fantasia / Aventura', 'Nobres Vigaristas', '1', 'Livro físico', null, null, null, null, null, null, null),
  ('LIV0055', 'Anjos e Demônios', 'Dan Brown', 'Suspense', 'Mistério / Thriller', 'Robert Langdon', '1', 'Livro físico', null, null, null, null, null, null, null),
  ('LIV0056', 'O Código Da Vinci', 'Dan Brown', 'Suspense', 'Mistério / Thriller', 'Robert Langdon', '2', 'Livro físico', null, null, null, null, null, null, null),
  ('LIV0057', 'Ponto de Impacto', 'Dan Brown', 'Suspense', 'Thriller', null, null, 'Livro físico', null, null, null, null, null, null, null),
  ('LIV0058', 'Inferno', 'Dan Brown', 'Suspense', 'Mistério / Thriller', 'Robert Langdon', '4', 'Livro físico', null, null, null, null, null, null, null),
  ('LIV0059', 'O Símbolo Perdido', 'Dan Brown', 'Suspense', 'Mistério / Thriller', 'Robert Langdon', '3', 'Livro físico', null, null, null, null, null, null, null),
  ('LIV0060', 'O Clã dos Magos', 'Trudi Canavan', 'Fantasia', 'Fantasia', 'A Trilogia do Mago Negro', '1', 'Livro físico', null, null, null, null, null, null, null),
  ('LIV0061', 'A Aprendiz', 'Trudi Canavan', 'Fantasia', 'Fantasia', 'A Trilogia do Mago Negro', '2', 'Livro físico', null, null, null, null, null, null, null),
  ('LIV0062', 'O Lorde Supremo', 'Trudi Canavan', 'Fantasia', 'Fantasia', 'A Trilogia do Mago Negro', '3', 'Livro físico', null, null, null, null, null, null, null),
  ('LIV0063', 'O Desafio', 'David Malouf', 'Literatura', 'Romance histórico', null, null, 'Livro físico', null, null, null, null, null, null, null),
  ('LIV0064', 'O Coração dos Heróis', 'David Malouf', 'Literatura', 'Romance histórico', null, null, 'Livro físico', null, null, null, null, null, null, null),
  ('LIV0065', 'Anjos Caídos', 'Susan Ee', 'Fantasia', 'Distopia / Fantasia', 'Penryn e o Fim dos Dias', '1', 'Livro físico', null, null, null, null, null, null, null),
  ('LIV0066', 'O Que Aconteceu com Annie', 'C. J. Tudor', 'Suspense', 'Thriller', null, null, 'Livro físico', null, null, null, null, null, null, null),
  ('LIV0067', 'The Walking Dead: A Ascensão do Governador', 'Robert Kirkman e Jay Bonansinga', 'Terror / HQ', 'Zumbis', 'The Walking Dead - Romances', '1', 'Livro físico', null, null, null, null, null, null, null),
  ('LIV0068', 'The Walking Dead: O Caminho para Woodbury', 'Robert Kirkman e Jay Bonansinga', 'Terror / HQ', 'Zumbis', 'The Walking Dead - Romances', '2', 'Livro físico', null, null, null, null, null, null, null),
  ('LIV0069', 'The Walking Dead: A Queda do Governador - Parte 1', 'Robert Kirkman e Jay Bonansinga', 'Terror / HQ', 'Zumbis', 'The Walking Dead - Romances', '3', 'Livro físico', null, null, null, null, null, null, null),
  ('LIV0070', 'The Walking Dead: A Queda do Governador - Parte 2', 'Robert Kirkman e Jay Bonansinga', 'Terror / HQ', 'Zumbis', 'The Walking Dead - Romances', '4', 'Livro físico', null, null, null, null, null, null, null),
  ('LIV0071', 'The Walking Dead: A Invasão', 'Robert Kirkman e Jay Bonansinga', 'Terror / HQ', 'Zumbis', 'The Walking Dead - Romances', '5', 'Livro físico', null, null, null, null, null, null, null),
  ('LIV0072', 'The Walking Dead: Declínio', 'Robert Kirkman e Jay Bonansinga', 'Terror / HQ', 'Zumbis', 'The Walking Dead - Romances', '6', 'Livro físico', null, null, null, null, null, null, null),
  ('LIV0073', 'Naruto Gold', 'Masashi Kishimoto', 'Mangá / HQ', 'Shonen', 'Naruto Gold', null, 'Livro físico', null, null, null, null, null, null, null),
  ('LIV0074', 'A Batalha do Apocalipse: Da Queda dos Anjos ao Crepúsculo do Mundo', 'Eduardo Spohr', 'Fantasia', 'Fantasia épica', null, null, 'Livro físico', null, null, null, null, null, null, null),
  ('LIV0075', '1984', 'George Orwell', 'Literatura Clássica', 'Distopia', null, null, 'Livro físico', null, null, null, null, null, null, null),
  ('LIV0076', 'A Arte da Guerra', 'Sun Tzu', 'Estratégia', 'Clássico / Guerra', null, null, 'Livro físico', null, null, null, null, null, null, null),
  ('LIV0077', 'O Pequeno Príncipe', 'Antoine de Saint-Exupéry', 'Literatura', 'Fábula / Filosofia', null, null, 'Livro físico', null, null, null, null, null, null, null),
  ('LIV0078', 'O Apanhador no Campo de Centeio', 'J. D. Salinger', 'Literatura Clássica', 'Romance', null, null, 'Livro físico', null, null, null, null, null, null, null),
  ('LIV0079', 'O Livro da Filosofia', 'Vários autores', 'Filosofia', 'História da filosofia', null, null, 'Livro físico', null, null, null, null, null, null, null),
  ('LIV0080', 'O Segredo', 'Rhonda Byrne', 'Desenvolvimento Pessoal', 'Lei da atração', null, null, 'Livro físico', null, null, null, null, null, null, null),
  ('LIV0081', 'Jogo de Dentro', 'Desconhecido', 'Desenvolvimento Pessoal', 'Autoconhecimento', null, null, 'Livro físico', null, null, null, null, null, null, null),
  ('LIV0082', 'História Geral', 'Gilberto Cotrim', 'História', 'História geral', null, null, 'Livro físico', null, null, null, null, null, null, null),
  ('LIV0083', 'Fatos Aproximados', 'Eloisa James', 'Romance', 'Romance histórico', null, null, 'Livro físico', null, null, null, null, null, null, null),
  ('LIV0084', 'O Último Reino', 'Bernard Cornwell', 'Ficção Histórica', 'Saxões / Vikings', 'Crônicas Saxônicas', '1', 'Livro físico', null, null, null, null, null, null, null),
  ('LIV0085', 'O Cavaleiro da Morte', 'Bernard Cornwell', 'Ficção Histórica', 'Saxões / Vikings', 'Crônicas Saxônicas', '2', 'Livro físico', null, null, null, null, null, null, null),
  ('LIV0086', 'Os Senhores do Norte', 'Bernard Cornwell', 'Ficção Histórica', 'Saxões / Vikings', 'Crônicas Saxônicas', '3', 'Livro físico', null, null, null, null, null, null, null),
  ('LIV0087', 'A Canção da Espada', 'Bernard Cornwell', 'Ficção Histórica', 'Saxões / Vikings', 'Crônicas Saxônicas', '4', 'Livro físico', null, null, null, null, null, null, null),
  ('LIV0088', 'Terra em Chamas', 'Bernard Cornwell', 'Ficção Histórica', 'Saxões / Vikings', 'Crônicas Saxônicas', '5', 'Livro físico', null, null, null, null, null, null, null),
  ('LIV0089', 'Morte dos Reis', 'Bernard Cornwell', 'Ficção Histórica', 'Saxões / Vikings', 'Crônicas Saxônicas', '6', 'Livro físico', null, null, null, null, null, null, null),
  ('LIV0090', 'O Guerreiro Pagão', 'Bernard Cornwell', 'Ficção Histórica', 'Saxões / Vikings', 'Crônicas Saxônicas', '7', 'Livro físico', null, null, null, null, null, null, null),
  ('LIV0091', 'O Trono Vazio', 'Bernard Cornwell', 'Ficção Histórica', 'Saxões / Vikings', 'Crônicas Saxônicas', '8', 'Livro físico', null, null, null, null, null, null, null),
  ('LIV0092', 'Guerreiros da Tempestade', 'Bernard Cornwell', 'Ficção Histórica', 'Saxões / Vikings', 'Crônicas Saxônicas', '9', 'Livro físico', null, null, null, null, null, null, null),
  ('LIV0093', 'O Portador do Fogo', 'Bernard Cornwell', 'Ficção Histórica', 'Saxões / Vikings', 'Crônicas Saxônicas', '10', 'Livro físico', null, null, null, null, null, null, null),
  ('LIV0094', 'A Guerra do Lobo', 'Bernard Cornwell', 'Ficção Histórica', 'Saxões / Vikings', 'Crônicas Saxônicas', '11', 'Livro físico', null, null, null, null, null, null, null),
  ('LIV0095', 'A Espada dos Reis', 'Bernard Cornwell', 'Ficção Histórica', 'Saxões / Vikings', 'Crônicas Saxônicas', '12', 'Livro físico', null, null, null, null, null, null, null),
  ('LIV0096', 'O Senhor da Guerra', 'Bernard Cornwell', 'Ficção Histórica', 'Saxões / Vikings', 'Crônicas Saxônicas', '13', 'Livro físico', null, null, null, null, null, null, null),
  ('LIV0097', 'O Inimigo de Deus', 'Bernard Cornwell', 'Ficção Histórica', 'Lendas arturianas', 'As Crônicas de Artur', '2', 'Livro físico', null, null, null, null, null, null, null),
  ('LIV0098', 'O Condenado', 'Bernard Cornwell', 'Ficção Histórica', 'Histórico', null, null, 'Livro físico', null, null, null, null, null, null, null),
  ('LIV0099', 'Maldicão do Titã', 'Rick Riordan', 'Fantasia', 'Mitologia grega', 'Percy Jackson e os Olimpianos', '3', 'Livro físico', null, null, null, null, null, null, null),
  ('LIV0100', 'Jurassic Park', 'Michael Crichton', 'Ficção científica', 'Dinossauros / Thriller', null, null, 'Livro físico', null, null, null, null, null, null, null),
  ('LIV0101', 'Harry Potter e a Pedra Filosofal', 'J. K. Rowling', 'Fantasia', 'Bruxaria', 'Harry Potter', '1', 'Livro físico', null, null, null, null, null, null, null),
  ('LIV0102', 'Harry Potter e a Câmara Secreta', 'J. K. Rowling', 'Fantasia', 'Bruxaria', 'Harry Potter', '2', 'Livro físico', null, null, null, null, null, null, null),
  ('LIV0103', 'Harry Potter e o Prisioneiro de Azkaban', 'J. K. Rowling', 'Fantasia', 'Bruxaria', 'Harry Potter', '3', 'Livro físico', null, null, null, null, null, null, null),
  ('LIV0104', 'Harry Potter e o Cálice de Fogo', 'J. K. Rowling', 'Fantasia', 'Bruxaria', 'Harry Potter', '4', 'Livro físico', null, null, null, null, null, null, null),
  ('LIV0105', 'Harry Potter e a Ordem da Fênix', 'J. K. Rowling', 'Fantasia', 'Bruxaria', 'Harry Potter', '5', 'Livro físico', null, null, null, null, null, null, null),
  ('LIV0106', 'Harry Potter e o Enigma do Príncipe', 'J. K. Rowling', 'Fantasia', 'Bruxaria', 'Harry Potter', '6', 'Livro físico', null, null, null, null, null, null, null),
  ('LIV0107', 'Harry Potter e as Relíquias da Morte', 'J. K. Rowling', 'Fantasia', 'Bruxaria', 'Harry Potter', '7', 'Livro físico', null, null, null, null, null, null, null),
  ('LIV0108', 'Harry Potter e a Criança Amaldiçoada', 'J. K. Rowling, John Tiffany e Jack Thorne', 'Fantasia', 'Teatro / Bruxaria', 'Harry Potter', '8', 'Livro físico', null, null, null, null, null, null, null),
  ('LIV0109', 'Animais Fantásticos e Onde Habitam', 'J. K. Rowling', 'Fantasia', 'Bruxaria', 'Mundo Bruxo', null, 'Livro físico', null, null, null, null, null, null, null),
  ('LIV0110', 'Morte Súbita', 'J. K. Rowling', 'Literatura', 'Romance contemporâneo', null, null, 'Livro físico', null, null, null, null, null, null, null),
  ('LIV0111', 'O Ladrão de Raios', 'Rick Riordan', 'Fantasia', 'Mitologia grega', 'Percy Jackson e os Olimpianos', '1', 'Livro físico', null, null, null, null, null, null, null),
  ('LIV0112', 'O Mar de Monstros', 'Rick Riordan', 'Fantasia', 'Mitologia grega', 'Percy Jackson e os Olimpianos', '2', 'Livro físico', null, null, null, null, null, null, null),
  ('LIV0113', 'A Batalha do Labirinto', 'Rick Riordan', 'Fantasia', 'Mitologia grega', 'Percy Jackson e os Olimpianos', '4', 'Livro físico', null, null, null, null, null, null, null),
  ('LIV0114', 'O Último Olimpiano', 'Rick Riordan', 'Fantasia', 'Mitologia grega', 'Percy Jackson e os Olimpianos', '5', 'Livro físico', null, null, null, null, null, null, null),
  ('LIV0115', 'O Herói Perdido', 'Rick Riordan', 'Fantasia', 'Mitologia grega/romana', 'Os Heróis do Olimpo', '1', 'Livro físico', null, null, null, null, null, null, null),
  ('LIV0116', 'O Filho de Netuno', 'Rick Riordan', 'Fantasia', 'Mitologia grega/romana', 'Os Heróis do Olimpo', '2', 'Livro físico', null, null, null, null, null, null, null),
  ('LIV0117', 'A Marca de Atena', 'Rick Riordan', 'Fantasia', 'Mitologia grega/romana', 'Os Heróis do Olimpo', '3', 'Livro físico', null, null, null, null, null, null, null),
  ('LIV0118', 'A Casa de Hades', 'Rick Riordan', 'Fantasia', 'Mitologia grega/romana', 'Os Heróis do Olimpo', '4', 'Livro físico', null, null, null, null, null, null, null),
  ('LIV0119', 'O Sangue do Olimpo', 'Rick Riordan', 'Fantasia', 'Mitologia grega/romana', 'Os Heróis do Olimpo', '5', 'Livro físico', null, null, null, null, null, null, null),
  ('LIV0120', 'O Exorcista', 'William Peter Blatty', 'Terror', 'Horror religioso', null, null, 'Livro físico', null, null, null, null, null, null, null),
  ('LIV0121', 'Faixa de Impressão', 'Jeffery Archer', 'Romance', 'Drama / Suspense', null, null, 'Livro físico', null, null, null, null, null, null, null),
  ('LIV0122', 'Direito Constitucional: Questões de Concursos', 'Moraes', 'Direito', 'Direito Constitucional', null, null, 'Livro físico', null, null, null, null, null, null, null),
  ('LIV0123', 'Direito Civil e Criminal', 'Maria Helena Diniz', 'Direito', 'Direito Civil / Criminal', null, '4', 'Livro físico', null, null, null, null, null, null, null),
  ('LIV0124', 'Direito Civil: Direito de Família', 'Maria Helena Diniz', 'Direito', 'Direito Civil / Família', null, '5', 'Livro físico', null, null, null, null, null, null, null),
  ('LIV0125', 'Lições de Direito Aplicado', 'Desconhecido', 'Direito', 'Direito aplicado', null, null, 'Livro físico', null, null, null, null, null, null, null),
  ('LIV0126', 'Aplicação da Pena', 'Inácio de Carvalho Neto', 'Direito', 'Direito Penal', null, null, 'Livro físico', null, null, null, null, null, null, null),
  ('LIV0127', 'Amarilhas da Morte', 'Augusto Cury', 'Desenvolvimento Pessoal', 'Psicologia / Reflexão', null, null, 'Livro físico', null, null, null, null, null, null, null),
  ('LIV0128', 'A Incrível Expedição aos Dinossauros', 'Karen Dolby', 'Infantojuvenil', 'Dinossauros', null, null, 'Livro físico', null, null, null, null, null, null, null),
  ('LIV0129', 'Quatro Vidas de um Cachorro', 'W. Bruce Cameron', 'Romance', 'Animais / Drama', null, null, 'Livro físico', null, null, null, null, null, null, null),
  ('LIV0130', 'Anne de Green Gables', 'Lucy Maud Montgomery', 'Literatura Clássica', 'Romance / Infantojuvenil', 'Anne de Green Gables', '1', 'Livro físico', null, null, null, null, null, null, null),
  ('LIV0131', 'Diário de uma Banana: Vai ou Racha', 'Jeff Kinney', 'Infantojuvenil', 'Humor', 'Diário de um Banana', null, 'Livro físico', null, null, null, null, null, null, null),
  ('LIV0132', 'A Vida, o Universo e Tudo Mais', 'Douglas Adams', 'Ficção científica', 'Humor', 'O Guia do Mochileiro das Galáxias', '3', 'Livro físico', null, null, null, null, null, null, null),
  ('LIV0133', 'A Vida e o Mistério de Deus', 'Paul Hoffmann', 'Religião', 'Teologia', null, null, 'Livro físico', null, null, null, null, null, null, null),
  ('LIV0134', 'As Últimas Quatro Coisas', 'Paul Hoffmann', 'Religião', 'Teologia', null, null, 'Livro físico', null, null, null, null, null, null, null),
  ('LIV0135', 'O Bater de Suas Asas', 'Paul Hoffmann', 'Fantasia', 'Fantasia religiosa', 'Trilogia A Mão Esquerda de Deus', '3', 'Livro físico', null, null, null, null, null, null, null),
  ('LIV0136', 'O Pacto', 'Joe Hill', 'Terror', 'Sobrenatural', null, null, 'Livro físico', null, null, null, null, null, null, null),
  ('LIV0137', 'A Estrada da Noite', 'Joe Hill', 'Terror', 'Sobrenatural', null, null, 'Livro físico', null, null, null, null, null, null, null),
  ('LIV0138', 'A Arte da Guerra', 'Sun Tzu', 'Estratégia', 'Clássico / Guerra', null, null, 'Livro físico', null, null, null, null, null, null, null),
  ('LIV0139', 'Bonne & Clyde', 'Desconhecido', 'História / Biografia', 'Crime', null, null, 'Livro físico', null, null, null, null, null, null, null),
  ('LIV0140', 'O Último Templário', 'Raymond Khoury', 'Suspense', 'Histórico / Mistério', null, null, 'Livro físico', null, null, null, null, null, null, null),
  ('LIV0141', 'A Torre Negra: O Pistoleiro', 'Stephen King', 'Fantasia / Terror', 'Dark fantasy', 'A Torre Negra', '1', 'Livro físico', null, null, null, null, null, null, null),
  ('LIV0142', 'A Torre Negra: A Escolha dos Três', 'Stephen King', 'Fantasia / Terror', 'Dark fantasy', 'A Torre Negra', '2', 'Livro físico', null, null, null, null, null, null, null),
  ('LIV0143', 'A Torre Negra: As Terras Devastadas', 'Stephen King', 'Fantasia / Terror', 'Dark fantasy', 'A Torre Negra', '3', 'Livro físico', null, null, null, null, null, null, null),
  ('LIV0144', 'A Torre Negra: Mago e Vidro', 'Stephen King', 'Fantasia / Terror', 'Dark fantasy', 'A Torre Negra', '4', 'Livro físico', null, null, null, null, null, null, null),
  ('LIV0145', 'A Torre Negra: O Vento pela Fechadura', 'Stephen King', 'Fantasia / Terror', 'Dark fantasy', 'A Torre Negra', '4.5', 'Livro físico', null, null, null, null, null, null, null),
  ('LIV0146', 'A Torre Negra: A Torre Negra', 'Stephen King', 'Fantasia / Terror', 'Dark fantasy', 'A Torre Negra', '7', 'Livro físico', null, null, null, null, null, null, null),
  ('LIV0147', 'Histórias Extraordinárias', 'Edgar Allan Poe', 'Terror', 'Contos clássicos', null, null, 'Livro físico', null, null, null, null, null, null, null),
  ('LIV0148', 'Polícia Comunitária', 'Nazareno Marcineiro', 'Direito / Segurança Pública', 'Polícia comunitária', null, null, 'Livro físico', null, null, null, null, null, null, null),
  ('LIV0149', 'Ética Empresarial na Prática', 'Mário Sérgio Cortella e Américo Lacombe', 'Negócios', 'Ética empresarial', null, null, 'Livro físico', null, null, null, null, null, null, null),
  ('LIV0150', 'Gestão de Obras Públicas', 'Elisabete Coby Mourão', 'Administração Pública', 'Obras públicas', null, null, 'Livro físico', null, null, null, null, null, null, null),
  ('LIV0151', 'O Grande Livro da Mitologia Egípcia', 'Claudio Blanc', 'Mitologia', 'Egito antigo', null, null, 'Livro físico', null, null, null, null, null, null, null),
  ('LIV0152', 'As Profecias', 'Nostradamus', 'Esoterismo', 'Profecias', null, null, 'Livro físico', null, null, null, null, null, null, null),
  ('LIV0153', 'Ascensão das Trevas', 'Pacat', 'Fantasia', 'Fantasia', 'Ascensão das Trevas', null, 'Livro físico', null, null, null, null, null, null, null),
  ('LIV0154', 'As Nulidades no Processo Penal', 'Desconhecido', 'Direito', 'Processo Penal', null, null, 'Livro físico', null, null, null, null, null, null, null),
  ('LIV0155', 'Curso de Direito Civil Brasileiro: Responsabilidade Civil', 'Maria Helena Diniz', 'Direito', 'Direito Civil', null, '7', 'Saraiva', null, null, null, null, null, null, null),
  ('LIV0156', 'O Último Reino - Volume Único/Box', 'Bernard Cornwell', 'Ficção Histórica', 'Saxões / Vikings', 'Crônicas Saxônicas', null, 'Livro físico', null, null, null, null, null, null, null),
  ('LIV0157', 'Percy Jackson e os Olimpianos: Box/Volume', 'Rick Riordan', 'Fantasia', 'Mitologia grega', 'Percy Jackson e os Olimpianos', null, 'Livro físico', null, null, null, null, null, null, null),
  ('LIV0158', 'O Trono de Fogo', 'Rick Riordan', 'Fantasia', 'Mitologia egípcia', 'As Crônicas dos Kane', '2', 'Livro físico', null, null, null, null, null, null, null),
  ('LIV0159', 'A Pirâmide Vermelha', 'Rick Riordan', 'Fantasia', 'Mitologia egípcia', 'As Crônicas dos Kane', '1', 'Livro físico', null, null, null, null, null, null, null),
  ('LIV0160', 'O Filho de Netuno', 'Rick Riordan', 'Fantasia', 'Mitologia grega/romana', 'Os Heróis do Olimpo', '2', 'Livro físico', null, null, null, null, null, null, null),
  ('LIV0161', 'A Marca de Atena', 'Rick Riordan', 'Fantasia', 'Mitologia grega/romana', 'Os Heróis do Olimpo', '3', 'Livro físico', null, null, null, null, null, null, null),
  ('LIV0162', 'A Casa de Hades', 'Rick Riordan', 'Fantasia', 'Mitologia grega/romana', 'Os Heróis do Olimpo', '4', 'Livro físico', null, null, null, null, null, null, null)
on conflict (codigo) do update set
  titulo=excluded.titulo,
  autor=excluded.autor,
  tema=excluded.tema,
  subtema=excluded.subtema,
  colecao=excluded.colecao,
  volume=excluded.volume,
  editora_formato=excluded.editora_formato,
  isbn=excluded.isbn,
  paginas=excluded.paginas,
  ano=excluded.ano,
  localizacao=excluded.localizacao,
  capa_url=excluded.capa_url,
  observacoes=excluded.observacoes,
  tags=excluded.tags;
